# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d5146bf58dce091d4796f45566388cb4fb6d0a5229390ce3b017ffaace157c60cc07c683765e266140020780b7870c6fc062e89da42f7a4cf47e8d24963c55d

test:
  secret_key_base: f3037d017b739c051bb32421444a5b37831648dd3b8ba546e2130e73991bb2b4854154a1bb8a37e72ce5eec364d2e488cf33a29ee1b1efa4a76de04b74e273c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
